export const suggestionsList = [
  { name: "banana" },
  { name: "apple" },
  { name: "strawberries" },
  { name: "blueberries" },
  { name: "oranges" },
  { name: "grapes" },
  { name: "kiwi" },
  { name: "watermelon" },
  { name: "cantaloupe" },
  { name: "lettuce" },
  { name: "tomatoes" },
  { name: "cucumbers" },
  { name: "bell peppers" },
  { name: "carrots" },
  { name: "broccoli" },
  { name: "cauliflower" },
  { name: "potatoes" },
  { name: "onions" },
  { name: "garlic" },
  { name: "chicken breasts" },
  { name: "ground beef" },
  { name: "pork chops" },
  { name: "salmon" },
  { name: "shrimp" },
  { name: "eggs" },
  { name: "milk" },
  { name: "butter" },
  { name: "cheese" },
  { name: "yogurt" },
  { name: "bread" },
  { name: "bagels" },
  { name: "rice" },
  { name: "pasta" },
  { name: "cereal" },
  { name: "oatmeal" },
  { name: "cooking oil" },
  { name: "salt" },
  { name: "pepper" },
  { name: "sugar" },
  { name: "flour" },
  { name: "coffee" },
  { name: "tea" },
  { name: "orange juice" },
  { name: "soda" },
  { name: "bottled water" },
  { name: "chips" },
  { name: "cookies" },
  { name: "ice cream" },
  { name: "frozen pizza" },
  { name: "canned soup" },
  { name: "pasta sauce" },
  { name: "mayonnaise" },
  { name: "ketchup" },
  { name: "mustard" },
  { name: "pickles" },
  { name: "olive oil" },
  { name: "vinegar" },
  { name: "soy sauce" },
  { name: "spices" },
  { name: "toilet paper" },
  { name: "shampoo" },
  { name: "toothpaste" },
  { name: "soap" },
  { name: "laundry detergent" },
  { name: "dish soap" },
  { name: "trash bags" },
  { name: "aluminum foil" },
  { name: "batteries" },
  { name: "light bulbs" },
  { name: "paper towels" },
  { name: "napkins" },
  { name: "dishwasher detergent" },
  { name: "cat food" },
  { name: "dog food" },
  { name: "birdseed" },
  { name: "pet litter" },
  { name: "fertilizer" },
  { name: "insect repellent" },
  { name: "garbage cans" },
  { name: "vacuum cleaner bags" },
  { name: "cleaning supplies" },
  { name: "broom" },
  { name: "mop" },
  { name: "sponges" },
  { name: "trash cans" },
  { name: "gift wrap" },
  { name: "plastic containers" },
  { name: "ziplock bags" },
  { name: "matches" },
  { name: "charcoal" },
  { name: "lighter fluid" },
  { name: "firewood" },
  { name: "band-aids" },
  { name: "pain relievers" },
  { name: "vitamins" },
  { name: "allergy medicine" },
  { name: "cold medicine" },
  { name: "cough drops" },
  { name: "tissues" },
  { name: "razors" },
  { name: "shaving cream" },
  { name: "feminine hygiene products" },
  { name: "cotton balls" },
  { name: "cotton swabs" },
  { name: "nail polish" },
  { name: "hairbrush" },
  { name: "toothbrush" },
  { name: "floss" },
  { name: "makeup" },
  { name: "candles" },
  { name: "kitchen utensils" },
  { name: "food storage bags" },
  { name: "plastic wrap" },
  { name: "foil wrap" },
  { name: "dishwashing liquid" },
  { name: "dental floss" },
  { name: "hand sanitizer" },
  { name: "fabric softener" },
  { name: "scented candles" },
  { name: "kitchen towels" },
  { name: "oven cleaner" },
  { name: "stove cleaner" },
  { name: "sink cleaner" },
  { name: "dishwasher cleaner" },
  { name: "fridge cleaner" },
  { name: "floor cleaner" },
  { name: "bathroom cleaner" },
  { name: "glass cleaner" },
  { name: "toilet cleaner" },
  { name: "trash can liner" },
  { name: "baby wipes" },
  { name: "disinfectant wipes" },
  { name: "air freshener" },
  { name: "towel paper" },
  { name: "cling film" },
  { name: "sanitary pads" },
  { name: "shower gel" },
  { name: "body lotion" },
  { name: "shaving foam" },
  { name: "deodorant" },
  { name: "cotton pads" },
  { name: "hair conditioner" },
  { name: "hair gel" },
  { name: "hair spray" },
  { name: "mouthwash" },
  { name: "hand soap" },
  { name: "sanitary bags" },
  { name: "spinach" },
  { name: "avocado" },
  { name: "pineapple" },
  { name: "mango" },
  { name: "papaya" },
  { name: "pears" },
  { name: "asparagus" },
  { name: "brussels sprouts" },
  { name: "celery" },
  { name: "radishes" },
  { name: "zucchini" },
  { name: "sweet potatoes" },
  { name: "artichokes" },
  { name: "pomegranate" },
  { name: "apricots" },
  { name: "cherries" },
  { name: "plums" },
  { name: "blackberries" },
  { name: "raspberries" },
  { name: "peaches" },
  { name: "nectarines" },
  { name: "kiwifruit" },
  { name: "cranberries" },
  { name: "tofu" },
  { name: "quinoa" },
  { name: "couscous" },
  { name: "bulgur" },
  { name: "seitan" },
  { name: "tempeh" },
  { name: "almond milk" },
  { name: "soy milk" },
  { name: "coconut milk" },
  { name: "rice milk" },
  { name: "cashew milk" },
  { name: "oat milk" },
  { name: "hemp milk" },
  { name: "flaxseed milk" },
  { name: "almond butter" },
  { name: "peanut butter" },
  { name: "sunflower seed butter" },
  { name: "tahini" },
  { name: "greek yogurt" },
  { name: "cottage cheese" },
  { name: "sour cream" },
  { name: "whipping cream" },
  { name: "evaporated milk" },
  { name: "condensed milk" },
  { name: "gouda cheese" },
  { name: "swiss cheese" },
  { name: "brie cheese" },
  { name: "camembert cheese" },
  { name: "provolone cheese" },
  { name: "gruyere cheese" },
  { name: "blue cheese" },
  { name: "feta cheese" },
  { name: "roquefort cheese" },
  { name: "ricotta cheese" },
  { name: "ricotta salata cheese" },
  { name: "fontina cheese" },
  { name: "ghee" },
  { name: "naan bread" },
  { name: "rye bread" },
  { name: "whole wheat bread" },
  { name: "multigrain bread" },
  { name: "sourdough bread" },
  { name: "english muffins" },
  { name: "croissants" },
  { name: "baguette" },
  { name: "ciabatta" },
  { name: "focaccia" },
  { name: "tortillas" },
  { name: "lasagna noodles" },
  { name: "macaroni" },
  { name: "linguine" },
  { name: "vermicelli" },
  { name: "farfalle" },
  { name: "penne" },
  { name: "angel hair pasta" },
  { name: "gnocchi" },
  { name: "rice noodles" },
  { name: "orzo" },
  { name: "arborio rice" },
  { name: "basmati rice" },
  { name: "jasmine rice" },
  { name: "wild rice" },
  { name: "polenta" },
  { name: "granola" },
  { name: "pancake mix" },
  { name: "waffle mix" },
  { name: "baking powder" },
  { name: "baking soda" },
  { name: "cornstarch" },
  { name: "cinnamon" },
  { name: "nutmeg" },
  { name: "allspice" },
  { name: "ground cloves" },
  { name: "pumpkin pie spice" },
  { name: "bay leaves" },
  { name: "cumin" },
  { name: "paprika" },
  { name: "cilantro" },
  { name: "cabbage" },
  { name: "radicchio" },
  { name: "parsnips" },
  { name: "butternut squash" },
  { name: "okra" },
  { name: "leeks" },
  { name: "rutabaga" },
  { name: "scallions" },
  { name: "taro" },
  { name: "starfruit" },
  { name: "dragon fruit" },
  { name: "guava" },
  { name: "elderberries" },
  { name: "gooseberries" },
  { name: "kohlrabi" },
  { name: "swiss chard" },
  { name: "bok choy" },
  { name: "salsify" },
  { name: "yams" },
  { name: "watercress" },
  { name: "plantains" },
  { name: "jackfruit" },
  { name: "daikon radish" },
  { name: "jicama" },
  { name: "tamarind" },
  { name: "persimmons" },
  { name: "fennel" },
  { name: "black-eyed peas" },
  { name: "pinto beans" },
  { name: "kidney beans" },
  { name: "cannellini beans" },
  { name: "chickpeas" },
  { name: "lentils" },
  { name: "mung beans" },
  { name: "adzuki beans" },
  { name: "black beans" },
  { name: "navy beans" },
  { name: "lima beans" },
  { name: "fava beans" },
  { name: "sunflower seeds" },
  { name: "chia seeds" },
  { name: "flax seeds" },
  { name: "poppy seeds" },
  { name: "hemp seeds" },
  { name: "wheat germ" },
  { name: "wheat bran" },
  { name: "bulgur wheat" },
  { name: "millet" },
  { name: "barley" },
  { name: "oats" },
  { name: "farro" },
  { name: "spelt" },
  { name: "teff" },
  { name: "amaranth" },
  { name: "kamut" },
  { name: "macadamia nuts" },
  { name: "hazelnuts" },
  { name: "pecans" },
  { name: "brazil nuts" },
  { name: "cashews" },
  { name: "pistachios" },
  { name: "walnuts" },
  { name: "almonds" },
  { name: "chestnuts" },
  { name: "quail" },
  { name: "duck" },
  { name: "turkey" },
  { name: "cornish hen" },
  { name: "bison" },
  { name: "venison" },
  { name: "rabbit" },
  { name: "lamb" },
  { name: "goat" },
  { name: "ostrich" },
  { name: "elk" },
  { name: "duck eggs" },
  { name: "quail eggs" },
  { name: "goose eggs" },
  { name: "emu eggs" },
  { name: "alligator meat" },
  { name: "bison meat" },
  { name: "kangaroo meat" },
  { name: "wild boar" },
  { name: "rattlesnake meat" },
  { name: "escargot" },
  { name: "calamari" },
  { name: "clams" },
  { name: "mussels" },
  { name: "scallops" },
  { name: "lobster" },
  { name: "octopus" },
  { name: "oysters" },
  { name: "celery root" },
  { name: "beets" },
  { name: "watermelon radish" },
  { name: "acorn squash" },
  { name: "kale" },
  { name: "broccolini" },
  { name: "snow peas" },
  { name: "endive" },
  { name: "arugula" },
  { name: "butter lettuce" },
  { name: "borage" },
  { name: "sorrel" },
  { name: "tangelo" },
  { name: "guanabana" },
  { name: "soursop" },
  { name: "breadfruit" },
  { name: "star anise" },
  { name: "cayenne pepper" },
  { name: "garam masala" },
  { name: "coriander" },
  { name: "cardamom" },
  { name: "turmeric" },
  { name: "safron" },
  { name: "nutritional yeast" },
  { name: "agar agar" },
  { name: "tapioca pearls" },
  { name: "sushi rice" },
  { name: "soba noodles" },
  { name: "udon noodles" },
  { name: "ramen noodles" },
  { name: "pheasant" },
  { name: "alligator" },
  { name: "kangaroo" },
  { name: "boar" },
  { name: "chuck steak" },
  { name: "flank steak" },
  { name: "skirt steak" },
  { name: "hanger steak" },
  { name: "t-bone steak" },
  { name: "lamb chops" },
  { name: "veal" },
  { name: "bass" },
  { name: "halibut" },
  { name: "catfish" },
  { name: "mahi-mahi" },
  { name: "swordfish" },
  { name: "tilapia" },
  { name: "haddock" },
  { name: "anchovies" },
  { name: "trout" },
  { name: "arctic char" },
  { name: "lobster tail" },
  { name: "crab legs" },
  { name: "squid" },
  { name: "caviar" },
  { name: "freekeh" },
  { name: "hazelnut butter" },
  { name: "cashew butter" },
  { name: "pistachio butter" },
  { name: "pecan butter" },
  { name: "sunflower butter" },
  { name: "walnut butter" },
  { name: "hemp butter" },
  { name: "macadamia nut butter" },
  { name: "tiger nut butter" },
  { name: "goat cheese" },
  { name: "ricotta" },
  { name: "mascarpone" },
  { name: "paneer" },
  { name: "gorgonzola" },
  { name: "limburger" },
  { name: "camembert" },
  { name: "mimolette" },
  { name: "gjetost" },
  { name: "havarti" },
  { name: "fontina" },
  { name: "colby" },
  { name: "pepper jack" },
  { name: "gouda" },
  { name: "gruyere" },
  { name: "stilton" },
  { name: "pecorino" },
  { name: "manchego" },
  { name: "emmental" },
  { name: "raclette" },
  { name: "yucca" },
  { name: "celeriac" },
  { name: "daikon" },
  { name: "fiddlehead ferns" },
  { name: "hearts of palm" },
  { name: "yellowfin tuna" },
  { name: "sea bass" },
  { name: "cobia" },
  { name: "monkfish" },
  { name: "escolar" },
  { name: "tilefish" },
  { name: "grouper" },
  { name: "hake" },
  { name: "pollock" },
  { name: "sardines" },
  { name: "rainbow trout" },
  { name: "smelt" },
  { name: "kelp" },
  { name: "clamato" },
  { name: "root beer" },
  { name: "chai tea" },
  { name: "hibiscus tea" },
  { name: "kombucha" },
  { name: "coconut water" },
  { name: "energy drink" },
  { name: "sparkling water" },
  { name: "green smoothie" },
  { name: "wheatgrass" },
  { name: "oat bran" },
  { name: "spelt flour" },
  { name: "teff flour" },
  { name: "mesquite flour" },
  { name: "tapioca starch" },
  { name: "arrowroot" },
  { name: "chestnut flour" },
  { name: "potato flour" },
  { name: "rye flour" },
  { name: "chickpea flour" },
  { name: "cassava flour" },
  { name: "quinoa flour" },
  { name: "rye berries" },
  { name: "sorghum" },
  { name: "chocolate hazelnut spread" },
  { name: "honey butter" },
  { name: "fig preserves" },
  { name: "elderberry jam" },
  { name: "apricot jam" },
  { name: "mango chutney" },
  { name: "pickled ginger" },
  { name: "horseradish sauce" },
  { name: "remoulade" },
  { name: "aioli" },
  { name: "wasabi paste" },
  { name: "sesame oil" },
  { name: "grape seed oil" },
  { name: "palm oil" },
  { name: "avocado oil" },
  { name: "flaxseed oil" },
  { name: "walnut oil" },
  { name: "pistachio oil" },
  { name: "pumpkin seed oil" },
  { name: "poppy seed oil" },
  { name: "black truffle oil" },
  { name: "white truffle oil" },
  { name: "vegetable shortening" },
  { name: "lard" },
  { name: "duck fat" },
  { name: "beef tallow" },
  { name: "bacon fat" },
  { name: "suet" },
  { name: "fish sauce" },
  { name: "oyster sauce" },
  { name: "hoisin sauce" },
  { name: "teriyaki sauce" },
  { name: "mirin" },
  { name: "kombu" },
  { name: "wakame" },
  { name: "nori" },
  { name: "dulse" },
  { name: "umami paste" },
  { name: "miso" },
  { name: "hojicha" },
  { name: "oolong tea" },
  { name: "white tea" },
  { name: "pu-erh tea" },
  { name: "yerba mate" },
  { name: "kelp noodles" },
  { name: "spaghetti squash" },
  { name: "acai berries" },
  { name: "goji berries" },
  { name: "mulberries" },
  { name: "chayote" },
  { name: "water chestnuts" },
  { name: "bamboo shoots" },
  { name: "taro root" },
  { name: "rhubarb" },
  { name: "elderflower" },
  { name: "hibiscus petals" },
  { name: "chervil" },
  { name: "epazote" },
  { name: "lovage" },
  { name: "savory" },
  { name: "tarragon" },
  { name: "yuzu" },
  { name: "feijoa" },
  { name: "kiwano" },
  { name: "durian" },
  { name: "lychee" },
  { name: "longan" },
  { name: "miracle fruit" },
  { name: "horned melon" },
  { name: "yacon" },
  { name: "choy sum" },
  { name: "mustard greens" },
  { name: "collard greens" },
  { name: "dandelion greens" },
  { name: "amaranth greens" },
  { name: "water spinach" },
  { name: "broccoli rabe" },
  { name: "frisee" },
  { name: "purslane" },
  { name: "nopal cactus" },
  { name: "bamboo fungus" },
  { name: "enoki mushrooms" },
  { name: "maitake mushrooms" },
  { name: "shiitake mushrooms" },
  { name: "oyster mushrooms" },
  { name: "chanterelle mushrooms" },
  { name: "morel mushrooms" },
  { name: "truffle mushrooms" },
  { name: "lobster mushrooms" },
  { name: "hen of the woods mushrooms" },
  { name: "porcini mushrooms" },
  { name: "cremini mushrooms" },
  { name: "mung bean sprouts" },
  { name: "alfalfa sprouts" },
  { name: "broccoli sprouts" },
  { name: "sunflower sprouts" },
  { name: "chive blossoms" },
  { name: "squash blossoms" },
  { name: "hibiscus flowers" },
  { name: "lavender buds" },
  { name: "rose petals" },
  { name: "violet flowers" },
  { name: "marigold petals" },
  { name: "saffron threads" },
  { name: "vanilla beans" },
  { name: "sumac" },
  { name: "fennel seeds" },
  { name: "mustard seeds" },
  { name: "fenugreek seeds" },
  { name: "caraway seeds" },
  { name: "nigella seeds" },
  { name: "smoked paprika" },
  { name: "chili powder" },
  { name: "curry powder" },
  { name: "cumin seeds" },
  { name: "coriander seeds" },
  { name: "fenugreek leaves" },
  { name: "safflower oil" },
  { name: "pomegranate molasses" },
  { name: "apple cider vinegar" },
  { name: "rice vinegar" },
  { name: "balsamic glaze" },
  { name: "sambal oelek" },
  { name: "gochujang" },
  { name: "harissa" },
  { name: "tamarind paste" },
  { name: "ume plum vinegar" },
  { name: "sake" },
  { name: "rice wine" },
  { name: "glass noodles" },
  { name: "sweet potato noodles" },
  { name: "quinoa pasta" },
  { name: "black bean pasta" },
  { name: "chickpea pasta" },
  { name: "lentil pasta" },
  { name: "seaweed snacks" },
  { name: "wasabi peas" },
  { name: "rice crackers" },
  { name: "ginseng tea" },
  { name: "dandelion root tea" },
  { name: "chamomile tea" },
  { name: "peppermint tea" },
  { name: "echinacea tea" },
  { name: "elderflower tea" },
  { name: "chaga tea" },
  { name: "nettle tea" },
  { name: "rooibos tea" },
  { name: "bancha tea" },
  { name: "yerba mate tea" },
  { name: "lapsang souchong" },
  { name: "sage tea" },
  { name: "lemongrass tea" },
  { name: "tarragon tea" },
  { name: "comfrey tea" },
  { name: "calendula tea" },
  { name: "mugwort tea" },
  { name: "sassafras tea" },
  { name: "yarrow tea" },
  { name: "catnip tea" },
  { name: "rosehip tea" },
  { name: "marshmallow root tea" },
  { name: "slippery elm tea" },
  { name: "dragonfruit" },
  { name: "boysenberries" },
  { name: "kumquats" },
  { name: "tangelos" },
  { name: "clementines" },
  { name: "black currants" },
  { name: "quince" },
  { name: "wasabi" },
  { name: "saffron" },
  { name: "coconut flour" },
  { name: "plantain flour" },
  { name: "amaranth flour" },
  { name: "tapioca flour" },
  { name: "lotus root" },
  { name: "bitter melon" },
  { name: "sun-dried tomatoes" },
  { name: "sundried apricots" },
  { name: "sultanas" },
  { name: "golden raisins" },
  { name: "black garlic" },
  { name: "fermented tofu" },
  { name: "natto" },
  { name: "tempeh bacon" },
  { name: "smoked tofu" },
  { name: "pandan leaves" },
  { name: "kaffir lime leaves" },
  { name: "lemongrass" },
  { name: "galangal" },
  { name: "turmeric root" },
  { name: "burdock root" },
  { name: "lotus seeds" },
  { name: "arrowroot flour" },
  { name: "red lentils" },
  { name: "black lentils" },
  { name: "pigeon peas" },
  { name: "yellow split peas" },
  { name: "butter beans" },
  { name: "pea shoots" },
  { name: "romaine lettuce" },
  { name: "chard" },
  { name: "turnip greens" },
  { name: "napa cabbage" },
  { name: "cherimoya" },
  { name: "rambutan" },
  { name: "linden flowers" },
  { name: "chamomile flowers" },
  { name: "passionflower" },
  { name: "valerian root" },
  { name: "cat's claw" },
  { name: "echinacea" },
  { name: "ginkgo biloba" },
  { name: "turmeric supplements" },
  { name: "black cohosh" },
  { name: "astragalus" },
  { name: "valerian root supplements" },
  { name: "ginseng supplements" },
  { name: "milk thistle" },
  { name: "kava kava" },
  { name: "stevia" },
  { name: "monk fruit sweetener" },
  { name: "xylitol" },
  { name: "erythritol" },
  { name: "stevia leaf extract" },
  { name: "sucralose" },
  { name: "saccharin" },
  { name: "aspartame" },
  { name: "cyclamate" },
  { name: "neotame" },
  { name: "palm sugar" },
  { name: "coconut sugar" },
  { name: "maple syrup" },
  { name: "agave nectar" },
  { name: "date syrup" },
  { name: "molasses" },
  { name: "barley malt syrup" },
  { name: "rice syrup" },
  { name: "sorghum syrup" },
  { name: "blood oranges" },
  { name: "seville oranges" },
  { name: "meyer lemons" },
  { name: "quinces" },
  { name: "cardamom pods" },
  { name: "anise seeds" },
  { name: "dill seeds" },
];
